# -*- coding: utf-8 -*-
"""myhackie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Ju6ySxBWCxzEu3VDSBZHGUjCuf2XzWn
"""

import numpy as np
import pandas as pd
import io
from sklearn import linear_model
from google.colab import files

uploaded = files.upload()
dat = pd.read_csv(io.BytesIO(uploaded['predictivedat.csv']))

x = dat[['lat', 'long', 'apr_temp', 'may_temp', 'june_temp', 'july_temp',  'aug_temp',
        'apr_rain', 'may_rain', 'june_rain', 'july_rain', 'aug_rain']]
y = dat['date_fire']
 
# with rename the
lm = linear_model.LinearRegression()
mod = lm.fit(x, y)

print('Intercept: \n', mod.intercept_)
print('Coefficients: \n', mod.coef_)

user_dat = pd.DataFrame(np.array([[-116.419338, 50.905458, 15, 20, 22, 30, 30, 4, 5, 5, 5, 6]]),
                   columns=['lat', 'long', 'apr_temp', 'may_temp', 'june_temp', 'july_temp', 'aug_temp', 
                            'apr_rain', 'may_rain', 'june_rain', 'july_rain', 'aug_rain'])
print(user_dat)

predicted_val = mod.predict(user_dat)
print(predicted_val)

# high risk
lati = -116.5
longi = 51
temp4 = 16
temp5 = 19
temp6 = 22
temp7 = 30
temp8 = 28
rain4 = 6
rain5 = 5
rain6 = 5
rain7 = 7
rain8 = 5

# combine user input value variables into data frame
user_dat = pd.DataFrame(np.array([[lati, longi, temp4, temp5, temp6, temp7, temp8,
                                   rain4, rain5, rain6, rain7, rain8]]),
                   columns=['lat', 'long', 'apr_temp', 'may_temp', 'june_temp', 'july_temp', 'aug_temp', 
                            'apr_rain', 'may_rain', 'june_rain', 'july_rain', 'aug_rain'])
print(user_dat)